# Crash Information
AppName: Europa Universalis V 
AppVersion: 1.0.9 
SCMBranch: release/1.0.9 
SCMCommit: 8e008095761995f2c3ca3685f2535a4ca2142007 
SCMTimeStamp: "2025-12-03 10:29:16 +0000" 
CWVersion: 2025.47.0 
CWSCMBranch: caesar/release/1.0.9 
CWSCMCommit: a3101aae5d044716ab9a81d6ab5d3e81082366aa 
CWSCMTimeStamp: "2025-11-20 15:01:07 +0000" 
DateTime: "0125-11-05 03:55:25 +0000" 
BuildType: ReleaseLto 
Platform: Windows 
Store: steam 
Architecture: 64-bit 
OperatingSystem: Windows 11 (Build 26200) 
SystemLanguage: en 
CPUModel: AMD Ryzen 7 5800X 8-Core Processor              
CPUSpeed: 3800 
CPUPhysicalCores: 8 
CPULogicalCores: 16 
SystemMemoryAvailable: 11995 
SystemMemory: 32694 
SwapSizeAvailable: 20027 
SwapSize: 51321 
GPUName: NVIDIA GeForce RTX 2060 
GPUVendor: nVidia 
GPUId: 7817 
GPUDedicatedMemory: 5945 
GPUDedicatedMemoryUsed: 2559 
GPUDriverVersion: 32.0.15.8157 
RenderAPI: dx12 
LaunchArguments: --antiloop --antiloopmultiplier="" --high --steam 
DLC_1: Ancient Monument Pack 
DLC_2: Shared DLC Data 
DLC_3: Sacred Sites 
Mod_1: Lucky Donation 
